/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.gamespice.android.scaffold;

public class gamespice_staticJNI {
  public final static native long new_vectorS__SWIG_0();
  public final static native long new_vectorS__SWIG_1(long jarg1);
  public final static native long vectorS_size(long jarg1, vectorS jarg1_);
  public final static native long vectorS_capacity(long jarg1, vectorS jarg1_);
  public final static native void vectorS_reserve(long jarg1, vectorS jarg1_, long jarg2);
  public final static native boolean vectorS_isEmpty(long jarg1, vectorS jarg1_);
  public final static native void vectorS_clear(long jarg1, vectorS jarg1_);
  public final static native void vectorS_add(long jarg1, vectorS jarg1_, String jarg2);
  public final static native String vectorS_get(long jarg1, vectorS jarg1_, int jarg2);
  public final static native void vectorS_set(long jarg1, vectorS jarg1_, int jarg2, String jarg3);
  public final static native void delete_vectorS(long jarg1);
  public final static native long new_FacebookCallback();
  public final static native void FacebookCallback_onLogin(long jarg1, FacebookCallback jarg1_);
  public final static native void FacebookCallback_onInviteFriendsComplete(long jarg1, FacebookCallback jarg1_, long jarg2, vectorS jarg2_, String jarg3);
  public final static native void FacebookCallback_onShareComplete(long jarg1, FacebookCallback jarg1_, String jarg2);
  public final static native void FacebookCallback_onBragComplete(long jarg1, FacebookCallback jarg1_, String jarg2);
  public final static native void FacebookCallback_onPostScoreComplete(long jarg1, FacebookCallback jarg1_);
  public final static native void FacebookCallback_onUnlockAchievementComplete(long jarg1, FacebookCallback jarg1_);
  public final static native void delete_FacebookCallback(long jarg1);
}
