/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.gamespice.android;

public class vectorS {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected vectorS(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(vectorS obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gamespice_staticJNI.delete_vectorS(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public vectorS() {
    this(gamespice_staticJNI.new_vectorS__SWIG_0(), true);
  }

  public vectorS(long n) {
    this(gamespice_staticJNI.new_vectorS__SWIG_1(n), true);
  }

  public long size() {
    return gamespice_staticJNI.vectorS_size(swigCPtr, this);
  }

  public long capacity() {
    return gamespice_staticJNI.vectorS_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    gamespice_staticJNI.vectorS_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return gamespice_staticJNI.vectorS_isEmpty(swigCPtr, this);
  }

  public void clear() {
    gamespice_staticJNI.vectorS_clear(swigCPtr, this);
  }

  public void add(String x) {
    gamespice_staticJNI.vectorS_add(swigCPtr, this, x);
  }

  public String get(int i) {
    return gamespice_staticJNI.vectorS_get(swigCPtr, this, i);
  }

  public void set(int i, String val) {
    gamespice_staticJNI.vectorS_set(swigCPtr, this, i, val);
  }

}
